events {}

http {
    upstream productscluster {
        server products:8484;
    }

    upstream cartcluster {
        server cart:8383;
    }

    server {
        listen 80;

        location /products/ {
            proxy_pass http://productscluster/products/;
        }

        location /cart/ {
            proxy_pass http://cartcluster/cart/;
        }
    }
}
