events {}

http {
    upstream productscluster {
        server products:8484;
    }

    upstream cartcluster {
        server cart:8383;
    }

    server {
        listen 80;

        # Configuración general de CORS para todos los servicios
        # Ajusta localhost:4200 si tu Angular usa otro puerto
        add_header 'Access-Control-Allow-Origin' 'http://localhost:4200' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin' always;

        location /products/ {
            # Manejo de la petición Pre-flight (OPTIONS)
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' 'http://localhost:4200' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
                add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin' always;
                add_header 'Content-Length' 0;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                return 204;
            }
            proxy_pass http://productscluster/products/;
        }

        location /cart/ {
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' 'http://localhost:4200' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
                add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin' always;
                add_header 'Content-Length' 0;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                return 204;
            }
            proxy_pass http://cartcluster/cart/;
        }
    }
}